; **** generated by scanner.py ****


; ***** - *****

word_def__macro_2d:
        ld a,end_word_def__macro_2d-word_def__macro_2d-3-2
        call MacroExpander
        ld         b,h                                 ; value to subtract in BC
        ld         c,l
        ld        h,d                                 ; value to subtract from in HL
        ld         l,e
        xor      a                                     ; clear carry
        sbc     hl,bc                                 ; and subtract.
end_word_def__macro_2d:

; ***** + *****

word_def__macro_2b:
        ld a,end_word_def__macro_2b-word_def__macro_2b-3-2
        call MacroExpander
        add         hl,de
end_word_def__macro_2b:

; ***** * *****

word_def__macro_2a:
        ld a,end_word_def__macro_2a-word_def__macro_2a-3-2
        call MacroExpander
        call    Multiply16
end_word_def__macro_2a:

; ***** c@ *****

word_def__macro_63_40:
        ld a,end_word_def__macro_63_40-word_def__macro_63_40-3-2
        call MacroExpander
        ld         l,(hl)
        ld         h,0
end_word_def__macro_63_40:

; ***** c! *****

word_def__macro_63_21:
        ld a,end_word_def__macro_63_21-word_def__macro_63_21-3-2
        call MacroExpander
        ld         (hl),e
end_word_def__macro_63_21:

; ***** @ *****

word_def__macro_40:
        ld a,end_word_def__macro_40-word_def__macro_40-3-2
        call MacroExpander
        ld         a,(hl)
        inc     hl
        ld         h,(hl)
        ld         l,a
end_word_def__macro_40:

; ***** ! *****

word_def__macro_21:
        ld a,end_word_def__macro_21-word_def__macro_21-3-2
        call MacroExpander
        ld         (hl),e
        inc     hl
        ld         (hl),d
        dec     hl
end_word_def__macro_21:

; ***** false *****

word_def__macro_66_61_6c_73_65:
        ld a,end_word_def__macro_66_61_6c_73_65-word_def__macro_66_61_6c_73_65-3-2
        call MacroExpander
        ex         de,hl
        ld         hl,$0000
end_word_def__macro_66_61_6c_73_65:

; ***** pop.ab *****

word_def__macro_70_6f_70_2e_61_62:
        ld a,end_word_def__macro_70_6f_70_2e_61_62-word_def__macro_70_6f_70_2e_61_62-3-2
        call MacroExpander
        pop     hl
        pop     de
end_word_def__macro_70_6f_70_2e_61_62:

; ***** pop.bb *****

word_def__macro_70_6f_70_2e_62_62:
        ld a,end_word_def__macro_70_6f_70_2e_62_62-word_def__macro_70_6f_70_2e_62_62-3-2
        call MacroExpander
        pop     de
        pop     de
end_word_def__macro_70_6f_70_2e_62_62:

; ***** push.ab *****

word_def__macro_70_75_73_68_2e_61_62:
        ld a,end_word_def__macro_70_75_73_68_2e_61_62-word_def__macro_70_75_73_68_2e_61_62-3-2
        call MacroExpander
            push     de
            push     hl
end_word_def__macro_70_75_73_68_2e_61_62:

; ***** a>r *****

word_def__macro_61_3e_72:
        ld a,end_word_def__macro_61_3e_72-word_def__macro_61_3e_72-3-2
        call MacroExpander
        push     hl
end_word_def__macro_61_3e_72:

; ***** ; *****

word_def__macro_3b:
        ld a,end_word_def__macro_3b-word_def__macro_3b-3-2
        call MacroExpander
        ret
end_word_def__macro_3b:

; ***** r>a *****

word_def__macro_72_3e_61:
        ld a,end_word_def__macro_72_3e_61-word_def__macro_72_3e_61-3-2
        call MacroExpander
        ex         de,hl
        pop     hl
end_word_def__macro_72_3e_61:

; ***** true *****

word_def__macro_74_72_75_65:
        ld a,end_word_def__macro_74_72_75_65-word_def__macro_74_72_75_65-3-2
        call MacroExpander
        ex         de,hl
        ld         hl,$FFFF
end_word_def__macro_74_72_75_65:

; ***** a>b *****

word_def__macro_61_3e_62:
        ld a,end_word_def__macro_61_3e_62-word_def__macro_61_3e_62-3-2
        call MacroExpander
        ld         d,h
        ld         e,l
end_word_def__macro_61_3e_62:

; ***** b>a *****

word_def__macro_62_3e_61:
        ld a,end_word_def__macro_62_3e_61-word_def__macro_62_3e_61-3-2
        call MacroExpander
        ld         h,d
        ld         l,e
end_word_def__macro_62_3e_61:

; ***** swap *****

word_def__macro_73_77_61_70:
        ld a,end_word_def__macro_73_77_61_70-word_def__macro_73_77_61_70-3-2
        call MacroExpander
        ex         de,hl
end_word_def__macro_73_77_61_70:

; ***** breakpoint *****

word_def__macro_62_72_65_61_6b_70_6f_69_6e_74:
        ld a,end_word_def__macro_62_72_65_61_6b_70_6f_69_6e_74-word_def__macro_62_72_65_61_6b_70_6f_69_6e_74-3-2
        call MacroExpander
        db         $DD,$01
end_word_def__macro_62_72_65_61_6b_70_6f_69_6e_74:

; ***** halt *****

word_def__macro_68_61_6c_74:
        ld a,end_word_def__macro_68_61_6c_74-word_def__macro_68_61_6c_74-3-2
        call MacroExpander
HaltProcessor:
        halt                                         ; halt that enables interrupt.
        jr         HaltProcessor
end_word_def__macro_68_61_6c_74:

; ***** 1- *****

word_def__macro_31_2d:
        ld a,end_word_def__macro_31_2d-word_def__macro_31_2d-3-2
        call MacroExpander
        dec     hl
end_word_def__macro_31_2d:

; ***** 1+ *****

word_def__macro_31_2b:
        ld a,end_word_def__macro_31_2b-word_def__macro_31_2b-3-2
        call MacroExpander
        inc     hl
end_word_def__macro_31_2b:

; ***** 2/ *****

word_def__macro_32_2f:
        ld a,end_word_def__macro_32_2f-word_def__macro_32_2f-3-2
        call MacroExpander
        sra     h
        rr         l
end_word_def__macro_32_2f:

; ***** 2- *****

word_def__macro_32_2d:
        ld a,end_word_def__macro_32_2d-word_def__macro_32_2d-3-2
        call MacroExpander
        dec     hl
        dec     hl
end_word_def__macro_32_2d:

; ***** 2+ *****

word_def__macro_32_2b:
        ld a,end_word_def__macro_32_2b-word_def__macro_32_2b-3-2
        call MacroExpander
        inc     hl
        inc     hl
end_word_def__macro_32_2b:

; ***** 2* *****

word_def__macro_32_2a:
        ld a,end_word_def__macro_32_2a-word_def__macro_32_2a-3-2
        call MacroExpander
        add     hl,hl
end_word_def__macro_32_2a:

; ***** bswap *****

word_def__macro_62_73_77_61_70:
        ld a,end_word_def__macro_62_73_77_61_70-word_def__macro_62_73_77_61_70-3-2
        call MacroExpander
        ld         a,h
        ld         h,l
        ld         l,a
end_word_def__macro_62_73_77_61_70:
